pid /tmp/nginx.pid;
events {}
http {
  access_log off;
  client_body_temp_path /tmp/client;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;
  server {
    listen 8081;
    listen 8443 ssl;
    ssl_certificate /etc/aster/tls/tls.crt;
    ssl_certificate_key /etc/aster/tls/tls.key;
    location / {
      proxy_pass http://authentik-demo-server.aster-authentik.svc.cluster.local;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
