apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-contracts
  labels:
    app.kubernetes.io/name: aster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: aster
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
{{- range $name, $body := .Values.contracts }}
  {{ $name }}.json: |-
{{ $body | indent 4 }}
{{- end }}
{{- if not .Values.contracts }}
  {}
{{- end }}
